# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell

# The grid certificate. The rows below come from the functions the server
# runs (`count_verdict`, `fibre`), rendered as an Agda module. Agda then
# proves by `refl` that its own closed forms produce the same table
# (agda/src/MetaManifold/Evidence/CountsCertificate.agda). That is a check of
# this Julia code on the grid, not a proof of it; the closed forms themselves
# are proved for all naturals.

"""
    CERTIFICATE_BOUND

The largest read count and noise bound on the certified grid.
"""
const CERTIFICATE_BOUND = 12

"""
    certificate_rows(k = CERTIFICATE_BOUND)

Every `(reads, noise_bound, verdict, lo, hi)` for reads and noise bound in
`0:k`, reads outermost, computed by `count_verdict` and `fibre`.
"""
function certificate_rows(k::Integer = CERTIFICATE_BOUND)
    return [(y, n, count_verdict(y, n), fibre(y, n).lo, fibre(y, n).hi)
            for y in 0:k for n in 0:k]
end

"""
    certificate_agda(k = CERTIFICATE_BOUND) -> String

The text of `CountsJuliaTable.agda`: `certificate_rows(k)` as an Agda list.
"""
function certificate_agda(k::Integer = CERTIFICATE_BOUND)
    io = IOBuffer()
    println(io, "{-# OPTIONS --safe --without-K #-}")
    println(io, "-- SPDX-License-Identifier: AGPL-3.0-or-later")
    println(io, "-- SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell")
    println(io, "--")
    println(io, "-- GENERATED by julia/gen/emit_table.jl from MetaManifoldEvidence.count_verdict")
    println(io, "-- and MetaManifoldEvidence.fibre over reads, noise in 0..$k. Do not edit.")
    println(io)
    println(io, "module MetaManifold.Evidence.CountsJuliaTable where")
    println(io)
    println(io, "open import Agda.Builtin.List using (List; []; _∷_)")
    println(io, "open import ResidualEvidence.Finite.Row using (entailed; refuted; unresolved; inconsistent)")
    println(io, "open import MetaManifold.Evidence.CountsGrid using (Row; row)")
    println(io)
    println(io, "expected : List Row")
    println(io, "expected =")
    for (y, n, v, lo, hi) in certificate_rows(k)
        println(io, "  row $y $n $(lowercase(string(v))) $lo $hi ∷")
    end
    println(io, "  []")
    return String(take!(io))
end
